# -*- coding: utf-8 -*-
"""Aula05_Manipulacao_Preparacao_Dados_IA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19_Xn3FrpDwRF8yn1Uj82oG5XdizQxYWV

# Aula — Manipulação e preparação de dados para modelos de IA

## Objetivos
- Manipular dados com Pandas
- Tratar valores faltantes
- Preparar dados para IA
- Criar gráficos simples
- Construir um pequeno pipeline
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""## Criando um dataset"""

dados = {
    'nome': ['Ana', 'Carlos', 'Maria', 'João', 'Pedro'],
    'idade': [20, 22, np.nan, 21, 23],
    'nota': [8.5, 7.0, 9.0, np.nan, 6.5],
    'faltas': [2, 5, 1, 3, np.nan]
}

df = pd.DataFrame(dados)

df

"""## Explorando os dados"""

df.info()

df.describe()

"""## Valores faltantes"""

df.isnull().sum()

"""## Tratando valores faltantes"""

df['idade'] = df['idade'].fillna(df['idade'].mean())
df['nota'] = df['nota'].fillna(df['nota'].mean())
df['faltas'] = df['faltas'].fillna(df['faltas'].mean())

df

"""## Filtrando dados"""

df[df['nota'] > 7]

"""## Criando nova coluna"""

df['situacao'] = df['nota'].apply(lambda x: 'Aprovado' if x >= 7 else 'Reprovado')

df

"""## Gráfico simples"""

plt.figure(figsize=(6,4))
plt.bar(df['nome'], df['nota'])
plt.xlabel('Aluno')
plt.ylabel('Nota')
plt.title('Notas dos alunos')
plt.show()

"""## Preparando dados para IA"""

X = df[['idade', 'faltas']]
y = df['nota']

print(X)
print(y)

"""## Dividindo treino e teste"""

from sklearn.model_selection import train_test_split

X_treino, X_teste, y_treino, y_teste = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print(len(X_treino))
print(len(X_teste))

"""## Modelo simples"""

from sklearn.linear_model import LinearRegression

modelo = LinearRegression()

modelo.fit(X_treino, y_treino)

previsoes = modelo.predict(X_teste)

previsoes

"""# Atividade prática

## Exercício 1
Mostre alunos com faltas menores que 3.

"""

df[df['faltas'] < 3]

"""## Exercício 2
Crie um gráfico das faltas.
"""

plt.figure(figsize=(6,4))
plt.bar(df['nome'], df['faltas'])
plt.xlabel('Aluno')
plt.ylabel('faltas')
plt.title('Faltas dos alunos')
plt.show()

"""## Exercício 3
Crie uma coluna chamada 'frequencia'.
"""

total_aulas = 20
df['frequencia'] = (((total_aulas - df['faltas']) / total_aulas) * 100).round(1).astype(str) + '%'
df

"""## Exercício 4
Qual variável parece ter mais relação com a nota?

REPOSTA: Embora a variável idade tenha apresentado a maior correlação numérica com a nota, isso não parece fazer muito sentido no contexto do problema. A variável faltas possui uma correlação negativa forte e apresenta uma relação mais coerente com a nota, já que alunos com mais faltas tendem a ter notas menores.
"""

df.corr(numeric_only=True)['nota']